name: Sync and Backup OpenHands

on:
  schedule:
    - cron: '0 3 * * *' # Chạy lúc 03:00 UTC mỗi ngày
  workflow_dispatch:     # Cho phép chạy thủ công

permissions:
  contents: read
  actions: read

jobs:
  sync-and-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cấu hình Git cho bot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Tạo file backup (demo)
        run: echo "Backup lúc $(date)" > backup-log.txt

      - name: Upload backup log lên GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup-log
          path: backup-log.txt
